version: '3.3'

volumes:
    sql_server_data: {}

services: 
    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sql_server
        ports: 
            - '7777:1433'
        volumes: 
            - sql_server_data:/var/opt/mssql
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=sql_server@zG3Wqmp9

